version: "3"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: testPassword
    container_name: navi_compose_mongodb
    ports:
      - 27017

  navi_auth:
    depends_on:
      mongodb:
        condition: service_started
    build:
      context: ./Navi-Authentication/.
      dockerfile: ./NaviAuth/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+
    volumes:
      - ./configurations/auth_config.json:/app/publish/appsettings.Development.json

  navi_gateway:
    depends_on:
      - navi_auth
      - swagger
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./configurations/nginx/test.conf:/etc/nginx/conf.d/default.conf
      - ./configurations/nginx/location-global.conf:/etc/nginx/conf.d/location-global.conf

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      URLS: '[
        {url: "./NaviAuthDefinition.yaml", name: "Navi Auth Service"}
        ]'
      BASE_URL: /swagger
    volumes:
      - ./Navi-Authentication/NaviAuth/Definition/NaviAuthDefinition.yaml:/usr/share/nginx/html/NaviAuthDefinition.yaml
